let varDefinitions = [{
  setting_key: 'CAPTURE_SHARED_URL_COUNT_DAYS_TTL',
  context: 'CLIENT.SECURITY',
  type: 'NUMERIC',
  description: 'Defines the number of days to store created shared urls',
  fallback_value: [],
  restrict: false,
  multi_value: false
},
{
  setting_key: 'LIMIT_SHARES_AMOUNT_CAPTURE_SHARED_URL_COUNT_DAYS_TTL',
  context: 'CAMPAIGN_VERSION.SECURITY',
  type: 'NUMERIC',
  description: `Defines if the lightbox show and share action should be limited by the amount of shares generated by an user. 
    This fetures requires CLIENT.SECURITY.CAPTURE_SHARED_URL_COUNT_DAYS_TTL config turned on.`,
  fallback_value: [],
  restrict: false,
  multi_value: false
}];

exports.up = function(knex) {

  return knex('reverb.var_definition')
    .insert(varDefinitions);
};

exports.down = function(knex) {

  return knex('reverb.var_definition')
    .whereIn('setting_key', varDefinitions.map(vd => vd.setting_key))
    .then((definitions) => {

      if(definitions){

        return knex('reverb.global_vars')
          .delete()
          .whereIn('var_definition_id', definitions.map(d => d._id))
          .then(() => {

            return knex('reverb.var_definition')
              .delete()
              .whereIn('setting_key', varDefinitions.map(vd => vd.setting_key));
          });
      }else {

        return knex('reverb.var_definition')
          .delete()
          .whereIn('setting_key', varDefinitions.map(vd => vd.setting_key));
      }

    });
};